apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhpam-ldap
  annotations:
    consoleName: snippet-rhpam-ldap-without-properties-file
    consoleTitle: Configure LDAP
    consoleDesc: Use this snippet to configure ldap opts using role mappning withiout a roles.properties file.
    consoleSnippet: true
spec:
  auth:
    ldap:
      url: ldaps://myldap.example.com
      bindDN: uid=admin,ou=users,ou=exmample,ou=com
      bindCredential: s3cret
      baseCtxDN: ou=users,ou=example,ou=com
      baseFilter: uid
      recursiveSearch: false
      roleAttributeID: memberOf
      rolesCtxDN: ou=groups,ou=example,ou=com
      roleFilter: (memberOf={1})
      defaultRole: guest
      newIdentityAttributes: sn=BlankSurname;cn=BlankCommonName
      referralMode: IGNORE
      loginFailover: true
    roleMapper:
      rolesProperties: admin=PowerUser,BillingAdmin;guest=guest;Administrator=admin,kie-server,rest-all;controllerUser=kie-server,rest-all
      rolesKeepMapped: true
      rolesKeepNonMapped: false

