apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: business-automation-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: business-automation-operator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: business-automation-operator
