apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhpam-standalone-dashbuilder
  annotations:
    consoleName: rhpam-standalone-dashbuilder
    consoleTitle: PAM Standalone Dashbuilder
    consoleDesc: Deploys a PAM Standalone Dashbuilder environment
spec:
  environment: rhpam-standalone-dashbuilder
